export interface ExecutiveBriefInput {
  operationsHealthScore: number | null;
  stockStatusCounts: { CRITICAL: number; LOW: number; HEALTHY: number; OVERSTOCKED: number };
  supplierReliability: { belowThresholdCount: number };
  overduePurchaseOrderCount: number;
  warehouseUtilizations: { warehouseName: string; utilizationPercent: number | null }[];
  warehouseCriticalThreshold: number;
}

/**
 * Produces a short, deterministic, plain-English summary of the current
 * operational situation from numbers the dashboard has already fetched —
 * no new calculation, purely templated sentences over already-computed
 * KPI values. Distinct from the AI narrative panel (Operations Copilot):
 * this always renders, requires no API key, and is never generated by an
 * LLM.
 */
export function buildExecutiveBrief(input: ExecutiveBriefInput): string[] {
  const lines: string[] = [];

  if (input.operationsHealthScore !== null) {
    const score = Math.round(input.operationsHealthScore);
    const tone = score >= 80 ? "in good shape" : score >= 60 ? "needs attention" : "requires immediate attention";
    lines.push(`Operations Health Score is ${score}/100 — overall operations are ${tone}.`);
  }

  if (input.stockStatusCounts.CRITICAL > 0) {
    lines.push(
      `${input.stockStatusCounts.CRITICAL} inventory position${input.stockStatusCounts.CRITICAL === 1 ? " is" : "s are"} critically low and at risk of stockout.`,
    );
  }

  if (input.stockStatusCounts.OVERSTOCKED > 0) {
    lines.push(
      `${input.stockStatusCounts.OVERSTOCKED} position${input.stockStatusCounts.OVERSTOCKED === 1 ? " is" : "s are"} overstocked, tying up working capital.`,
    );
  }

  if (input.supplierReliability.belowThresholdCount > 0) {
    lines.push(
      `${input.supplierReliability.belowThresholdCount} supplier${input.supplierReliability.belowThresholdCount === 1 ? " is" : "s are"} below the reliability threshold.`,
    );
  }

  if (input.overduePurchaseOrderCount > 0) {
    lines.push(
      `${input.overduePurchaseOrderCount} purchase order${input.overduePurchaseOrderCount === 1 ? " is" : "s are"} overdue for delivery.`,
    );
  }

  const utilizationValues = input.warehouseUtilizations.filter(
    (w): w is { warehouseName: string; utilizationPercent: number } => w.utilizationPercent !== null,
  );
  if (utilizationValues.length > 0) {
    const highest = utilizationValues.reduce((a, b) => (b.utilizationPercent > a.utilizationPercent ? b : a));
    const lowest = utilizationValues.reduce((a, b) => (b.utilizationPercent < a.utilizationPercent ? b : a));
    lines.push(
      `Warehouse utilization ranges from ${Math.round(lowest.utilizationPercent)}% (${lowest.warehouseName}) to ${Math.round(highest.utilizationPercent)}% (${highest.warehouseName}).`,
    );
    if (highest.utilizationPercent >= input.warehouseCriticalThreshold) {
      lines.push(`${highest.warehouseName} is nearing full capacity and may need relief.`);
    }
  }

  if (lines.length === 0 || (input.stockStatusCounts.CRITICAL === 0 && input.overduePurchaseOrderCount === 0 && input.supplierReliability.belowThresholdCount === 0)) {
    lines.push("No critical issues detected — operations are running smoothly.");
  }

  return lines;
}
