/**
 * Static, deterministic KPI explanations for the Executive Dashboard's
 * info popovers (DESIGN_SPECIFICATION.md §7.1). Every field here is fixed
 * copy — never AI-generated, never data-dependent — matching
 * OPERATIONS_ENGINE_SPEC.md's formulas and thresholds exactly, so this
 * file is the single source of truth to update if a formula ever changes.
 * "Current interpretation" (the one genuinely data-dependent field the
 * spec calls for) is deliberately NOT here — it's computed at render time
 * from the live value, see kpiInterpretation() below.
 */
export interface KpiInfoContent {
  definition: string;
  whyItMatters: string;
  howCalculated: string;
  idealRange: string;
  howToImprove: string[];
  /**
   * Optional — the concrete operational consequence of leaving this metric
   * unaddressed (Phase 5, Inventory Intelligence). Omitted by the original
   * six Dashboard KPI definitions below (their popovers render unchanged
   * without it — see KpiInfoPopover); every new Inventory KPI definition
   * includes it, since "what happens if I ignore it" is one of the five
   * questions the Inventory page is required to answer.
   */
  whatIfIgnored?: string;
}

export const KPI_DEFINITIONS = {
  operationsHealthScore: {
    definition:
      "A single 0–100 score blending inventory health, supplier reliability, forecast accuracy, warehouse balance, and inventory turnover into one headline number for the whole operation.",
    whyItMatters:
      "It's the fastest way to answer \"how are we doing today\" without checking five separate pages — a dropping score means at least one underlying area needs attention now.",
    howCalculated:
      "Weighted average: 35% inventory health + 20% supplier reliability + 20% forecast accuracy (100 − avg. forecast error) + 15% warehouse utilization health + 10% inventory turnover health. Any component with no data yet is excluded and the remaining weights are rescaled to still total 100%, so missing data never silently drags the score down.",
    idealRange: "80–100 is healthy. 60–79 needs attention. Below 60 requires immediate action.",
    howToImprove: [
      "Resolve critical and low-stock positions first — inventory health carries the largest single weight.",
      "Follow up with suppliers scoring below the reliability threshold.",
      "Keep demand forecasts current so their accuracy doesn't drag down the blend.",
    ],
  },
  inventoryTurnover: {
    definition:
      "How many times inventory is sold and replenished per year — cost of goods sold divided by current inventory value.",
    whyItMatters:
      "Too low suggests overstocking and slow-moving goods tying up capital; too high risks running unsafely close to stockouts.",
    howCalculated:
      "Annualized cost of goods sold ÷ current on-hand inventory value (unit cost × quantity, summed company-wide). Uses current stock as an approximation of average inventory value, since no historical snapshot exists yet.",
    idealRange: "Compared against a target of 8 turns/year for a general catalog — read alongside stockout risk, never in isolation.",
    howToImprove: [
      "Clear slow-moving, high-inventory-value SKUs (visible on the Analytics ABC breakdown).",
      "Tighten reorder quantities for consistently overstocked positions.",
      "Avoid chasing a higher number by cutting safety stock — that just trades this KPI for stockout risk.",
    ],
  },
  supplierReliability: {
    definition:
      "A 0–100 score per supplier, averaged company-wide, summarizing how dependable a supplier has been across delivery timing, timing consistency, and price stability.",
    whyItMatters:
      "A falling average — or a growing count of suppliers below threshold — is an early warning for procurement risk before it becomes a stockout.",
    howCalculated:
      "Equal-weighted average of three components, each 0–100: on-time delivery rate, lead-time consistency (inverse of delivery-time variance), and price stability (inverse of unit-cost variance). Requires at least 3 received purchase orders per supplier — suppliers with fewer stay unscored rather than defaulted to a misleading number.",
    idealRange: "70 and above is healthy. Below 70 is flagged as low-reliability.",
    howToImprove: [
      "Review suppliers below the reliability threshold and discuss recurring late deliveries directly.",
      "Diversify sourcing for critical SKUs single-sourced from a low-scoring supplier.",
      "Revisit contracted lead times that no longer match real delivery performance.",
    ],
  },
  activeRecommendations: {
    definition:
      "The count of currently open, unresolved recommendations generated by the rule engines — critical and warning severity combined.",
    whyItMatters:
      "This is the operational backlog: every item here represents a specific, already-identified action waiting on a decision.",
    howCalculated:
      "A live count of AIRecommendation rows with status ACTIVE, grouped by severity. Recomputed on every recalculation — resolving, snoozing, or dismissing a recommendation removes it from this count immediately.",
    idealRange: "There's no universal target — the goal is a shrinking or steady count, not zero (zero can also mean recalculation hasn't run recently).",
    howToImprove: [
      "Work critical-severity items first — they represent the highest-confidence, highest-impact triggers.",
      "Snooze items that are already being handled elsewhere so the active count reflects only what's truly outstanding.",
      "Run Recalculate All after any bulk data change so the list reflects current reality.",
    ],
  },
  forecastAccuracy: {
    definition:
      "How closely recent demand forecasts have matched actual sales, expressed as 100 minus the average forecast error (MAPE).",
    whyItMatters:
      "Low accuracy means downstream numbers that depend on forecasts — safety stock, reorder points, demand-increase recommendations — deserve more skepticism.",
    howCalculated:
      "Per period: |actual − forecast| ÷ actual × 100 = error. Averaged across all recent forecast periods (periods with zero actual sales are excluded, never treated as 0% error), then subtracted from 100.",
    idealRange: "Above 80% is trustworthy. Below 70% (MAPE above 30%) is the threshold below which demand-trend recommendations are deliberately suppressed.",
    howToImprove: [
      "Check for products with unusually volatile or sparse sales history — MAPE is naturally noisier for low-volume SKUs.",
      "Keep demand history current with regular imports so forecasts are trained on recent patterns.",
      "Compare the two forecasting methods per product on the Demand Forecasting page — one may consistently outperform the other for a given SKU.",
    ],
  },
  overduePurchaseOrders: {
    definition:
      "Purchase orders still marked in-transit whose expected delivery date has already passed.",
    whyItMatters:
      "Each one is a delivery promise already broken — a direct, immediate procurement risk, not a forecast or a trend.",
    howCalculated:
      "A live count of PurchaseOrder rows with status IN_TRANSIT and an expectedDeliveryDate earlier than right now.",
    idealRange: "Zero is the target — any count above zero is a live delivery risk worth following up today.",
    howToImprove: [
      "Contact the supplier on each overdue order for a revised delivery date.",
      "Check whether the affected SKUs also have a critical stock position — that combination is the highest-urgency case.",
      "Mark orders RECEIVED promptly once delivered, so this count doesn't overstate current risk.",
    ],
  },
  totalPositions: {
    definition: "The total number of product-warehouse inventory positions currently in view — one position per product per warehouse it's stocked in.",
    whyItMatters: "It's the scale of the picture everything else on this page describes — the denominator behind every critical/overstocked count and percentage.",
    howCalculated: "A live count of Inventory rows matching the current filters.",
    idealRange: "No ideal range — this is a scale measure, not a health measure.",
    howToImprove: [
      "Not directly actionable — use the Critical, Overstocked, and Health KPIs alongside this one to judge whether the count reflects a healthy or at-risk catalog.",
    ],
    whatIfIgnored: "N/A — this KPI describes scope, not risk, so there's nothing to act on directly.",
  },
  criticalInventoryPositions: {
    definition: "The number of positions where on-hand stock has fallen at or below the reorder point.",
    whyItMatters: "Each one is an active stockout risk — the product may run out before the next replenishment arrives.",
    howCalculated: "A live count of Inventory rows with stockStatus = CRITICAL (onHandQty ≤ reorderPoint), recomputed on every recalculation.",
    idealRange: "Zero is the target — any count above zero is a live stockout risk worth reviewing today.",
    howToImprove: [
      "Open each critical position's product detail page and check the Risk Explanation for the exact shortfall.",
      "Prioritize by lead time — a long-lead-time supplier needs a decision sooner than a short one.",
      "Cross-check the Procurement page for an EOQ suggestion already covering the same product.",
    ],
    whatIfIgnored: "The product runs out before restock arrives — lost sales (or halted operations, for non-resale inventory) until the next delivery lands.",
  },
  overstockedInventoryPositions: {
    definition: "The number of positions where on-hand stock exceeds 4x the reorder point.",
    whyItMatters: "Excess stock ties up working capital and warehouse space that could otherwise fund or hold faster-moving inventory.",
    howCalculated: "A live count of Inventory rows with stockStatus = OVERSTOCKED (onHandQty > 4 × reorderPoint), recomputed on every recalculation.",
    idealRange: "Zero is ideal, but unlike stockouts this is a capital-efficiency concern, not an urgent operational risk — a small steady count is common.",
    howToImprove: [
      "Pause or reduce standing purchase orders for consistently overstocked SKUs.",
      "Check whether the product's reorder point itself is outdated — falling demand can make a once-correct reorder point too generous over time.",
      "Consider a promotion or transfer to a warehouse with tighter supply, where sensible.",
    ],
    whatIfIgnored: "Capital and warehouse space stay locked in slow-moving stock instead of funding inventory that actually needs it.",
  },
  totalInventoryValue: {
    definition: "The total value of all on-hand inventory currently in view, at unit cost.",
    whyItMatters: "It's the working capital currently tied up on the shelf — the financial size of the operational picture this page describes.",
    howCalculated: "Sum of onHandQty × unitCost across every Inventory row matching the current filters.",
    idealRange: "No universal ideal range — read alongside Inventory Turnover to judge whether this value is being put to work or sitting idle.",
    howToImprove: [
      "Not directly actionable on its own — use the Critical and Overstocked KPIs to see which positions are driving this figure up or down.",
      "A high value concentrated in overstocked positions is the clearest sign of capital that could be freed up.",
    ],
    whatIfIgnored: "N/A — this KPI is a scale measure; the Overstocked KPI is where a genuinely actionable risk would show up.",
  },
  movingAverageAccuracy: {
    definition:
      "How closely this product's Moving Average forecast has matched actual demand, expressed as 100 minus the average forecast error (MAPE) across backtest periods.",
    whyItMatters:
      "Low accuracy for this product means its Moving Average forecast — and anything derived from it, like demand-trend recommendations — deserves more skepticism.",
    howCalculated:
      "Moving Average forecasts each period as the average of the preceding 4 periods' actual demand. Accuracy here is 100 minus the mean |actual − forecast| ÷ actual × 100 (MAPE) across this product's backtest periods.",
    idealRange: "Above 80% is trustworthy. Below 70% (MAPE above 30%) is the threshold below which demand-trend recommendations are deliberately suppressed for this product.",
    howToImprove: [
      "Moving Average responds slowly to recent shifts in demand — if this product's sales pattern has changed recently, Exponential Smoothing may track it more closely.",
      "Very volatile or low-volume products naturally produce a noisier MAPE regardless of method.",
      "Keep demand history current with regular imports so the averaging window reflects recent reality.",
    ],
  },
  exponentialSmoothingAccuracy: {
    definition:
      "How closely this product's Exponential Smoothing forecast has matched actual demand, expressed as 100 minus the average forecast error (MAPE) across backtest periods.",
    whyItMatters:
      "Low accuracy for this product means its Exponential Smoothing forecast — and anything derived from it, like demand-trend recommendations — deserves more skepticism.",
    howCalculated:
      "Exponential Smoothing forecasts each period as a weighted average of all preceding periods, weighted more heavily toward recent ones (smoothing factor α = 0.3). Accuracy here is 100 minus the mean |actual − forecast| ÷ actual × 100 (MAPE) across this product's backtest periods.",
    idealRange: "Above 80% is trustworthy. Below 70% (MAPE above 30%) is the threshold below which demand-trend recommendations are deliberately suppressed for this product.",
    howToImprove: [
      "Exponential Smoothing reacts faster to recent shifts than Moving Average — if this product has a stable, low-noise pattern instead, Moving Average may perform better.",
      "Very volatile or low-volume products naturally produce a noisier MAPE regardless of method.",
      "Keep demand history current with regular imports so recent periods are available to weight.",
    ],
  },
  abcClassification: {
    definition:
      "A ranking of every product by its annual usage value (annual demand × unit cost), grouped into three classes by cumulative share of that value: Class A (top ~80%), Class B (next ~15%), Class C (remaining ~5%).",
    whyItMatters:
      "It tells inventory managers where to focus — a small number of Class A products drive most of the value at stake, so they deserve tighter control and more attention than the long tail of Class C products.",
    howCalculated:
      "Products are ranked by usage value, descending. Running cumulative share of total usage value determines the cutoff: at or below 80% is Class A, 80-95% is Class B, the rest is Class C.",
    idealRange: "No universal ideal split — the useful read is which products fall in Class A, since those are the highest-value, highest-priority items regardless of exact counts.",
    howToImprove: [
      "Review Class A products first for stockout or overstock risk — they carry the most value at stake.",
      "Class C products can typically tolerate looser reorder policies without much financial impact.",
      "Use the Pareto Curve alongside this table to see the same ranking visually.",
    ],
  },
} satisfies Record<string, KpiInfoContent>;

export type KpiDefinitionKey = keyof typeof KPI_DEFINITIONS;

/**
 * The one genuinely data-dependent sentence in a KPI info panel — computed
 * from the live value, not stored as static copy. Still fully
 * deterministic (a template filled with a real number), never AI-generated.
 */
export function kpiCurrentInterpretation(key: KpiDefinitionKey, value: number | null): string {
  if (value === null) return "Not enough data yet to compute this metric.";

  switch (key) {
    case "operationsHealthScore":
      return value >= 80
        ? `Currently ${Math.round(value)}/100 — operations are in good shape.`
        : value >= 60
          ? `Currently ${Math.round(value)}/100 — needs attention in at least one area.`
          : `Currently ${Math.round(value)}/100 — requires immediate attention.`;
    case "inventoryTurnover":
      return value >= 8
        ? `Currently ${value.toFixed(1)}x/year — at or above the 8x target.`
        : `Currently ${value.toFixed(1)}x/year — below the 8x target, worth reviewing alongside stockout risk.`;
    case "supplierReliability":
      return value >= 70
        ? `Currently averaging ${Math.round(value)}/100 — above the reliability threshold.`
        : `Currently averaging ${Math.round(value)}/100 — below the 70-point reliability threshold.`;
    case "activeRecommendations":
      return `${Math.round(value)} recommendation${value === 1 ? "" : "s"} currently open.`;
    case "forecastAccuracy":
      return value >= 80
        ? `Currently ${value.toFixed(1)}% — forecasts are trustworthy.`
        : `Currently ${value.toFixed(1)}% — below the 80% trust threshold.`;
    case "overduePurchaseOrders":
      return value === 0
        ? "No purchase orders are currently overdue."
        : `${Math.round(value)} purchase order${value === 1 ? " is" : "s are"} currently overdue.`;
    case "totalPositions":
      return `${Math.round(value)} inventory position${value === 1 ? "" : "s"} in the current view.`;
    case "criticalInventoryPositions":
      return value === 0
        ? "No positions are currently critical."
        : `${Math.round(value)} position${value === 1 ? " is" : "s are"} critically low right now.`;
    case "overstockedInventoryPositions":
      return value === 0
        ? "No positions are currently overstocked."
        : `${Math.round(value)} position${value === 1 ? " is" : "s are"} overstocked right now.`;
    case "totalInventoryValue":
      return `Currently ₹${Math.round(value).toLocaleString("en-IN")} in on-hand inventory value.`;
    case "movingAverageAccuracy":
    case "exponentialSmoothingAccuracy":
      return value >= 80
        ? `Currently ${value.toFixed(1)}% for this product — trustworthy.`
        : `Currently ${value.toFixed(1)}% for this product — below the 80% trust threshold.`;
    case "abcClassification":
      return `${Math.round(value)} product(s) currently in Class A — the highest-priority segment.`;
    default:
      return "";
  }
}
