/**
 * Static, deterministic KPI explanations for the Executive Dashboard's
 * info popovers (DESIGN_SPECIFICATION.md §7.1). Every field here is fixed
 * copy — never AI-generated, never data-dependent — matching
 * OPERATIONS_ENGINE_SPEC.md's formulas and thresholds exactly, so this
 * file is the single source of truth to update if a formula ever changes.
 * "Current interpretation" (the one genuinely data-dependent field the
 * spec calls for) is deliberately NOT here — it's computed at render time
 * from the live value, see kpiInterpretation() below.
 */
export interface KpiInfoContent {
  definition: string;
  whyItMatters: string;
  howCalculated: string;
  idealRange: string;
  howToImprove: string[];
}

export const KPI_DEFINITIONS = {
  operationsHealthScore: {
    definition:
      "A single 0–100 score blending inventory health, supplier reliability, forecast accuracy, warehouse balance, and inventory turnover into one headline number for the whole operation.",
    whyItMatters:
      "It's the fastest way to answer \"how are we doing today\" without checking five separate pages — a dropping score means at least one underlying area needs attention now.",
    howCalculated:
      "Weighted average: 35% inventory health + 20% supplier reliability + 20% forecast accuracy (100 − avg. forecast error) + 15% warehouse utilization health + 10% inventory turnover health. Any component with no data yet is excluded and the remaining weights are rescaled to still total 100%, so missing data never silently drags the score down.",
    idealRange: "80–100 is healthy. 60–79 needs attention. Below 60 requires immediate action.",
    howToImprove: [
      "Resolve critical and low-stock positions first — inventory health carries the largest single weight.",
      "Follow up with suppliers scoring below the reliability threshold.",
      "Keep demand forecasts current so their accuracy doesn't drag down the blend.",
    ],
  },
  inventoryTurnover: {
    definition:
      "How many times inventory is sold and replenished per year — cost of goods sold divided by current inventory value.",
    whyItMatters:
      "Too low suggests overstocking and slow-moving goods tying up capital; too high risks running unsafely close to stockouts.",
    howCalculated:
      "Annualized cost of goods sold ÷ current on-hand inventory value (unit cost × quantity, summed company-wide). Uses current stock as an approximation of average inventory value, since no historical snapshot exists yet.",
    idealRange: "Compared against a target of 8 turns/year for a general catalog — read alongside stockout risk, never in isolation.",
    howToImprove: [
      "Clear slow-moving, high-inventory-value SKUs (visible on the Analytics ABC breakdown).",
      "Tighten reorder quantities for consistently overstocked positions.",
      "Avoid chasing a higher number by cutting safety stock — that just trades this KPI for stockout risk.",
    ],
  },
  supplierReliability: {
    definition:
      "A 0–100 score per supplier, averaged company-wide, summarizing how dependable a supplier has been across delivery timing, timing consistency, and price stability.",
    whyItMatters:
      "A falling average — or a growing count of suppliers below threshold — is an early warning for procurement risk before it becomes a stockout.",
    howCalculated:
      "Equal-weighted average of three components, each 0–100: on-time delivery rate, lead-time consistency (inverse of delivery-time variance), and price stability (inverse of unit-cost variance). Requires at least 3 received purchase orders per supplier — suppliers with fewer stay unscored rather than defaulted to a misleading number.",
    idealRange: "70 and above is healthy. Below 70 is flagged as low-reliability.",
    howToImprove: [
      "Review suppliers below the reliability threshold and discuss recurring late deliveries directly.",
      "Diversify sourcing for critical SKUs single-sourced from a low-scoring supplier.",
      "Revisit contracted lead times that no longer match real delivery performance.",
    ],
  },
  activeRecommendations: {
    definition:
      "The count of currently open, unresolved recommendations generated by the rule engines — critical and warning severity combined.",
    whyItMatters:
      "This is the operational backlog: every item here represents a specific, already-identified action waiting on a decision.",
    howCalculated:
      "A live count of AIRecommendation rows with status ACTIVE, grouped by severity. Recomputed on every recalculation — resolving, snoozing, or dismissing a recommendation removes it from this count immediately.",
    idealRange: "There's no universal target — the goal is a shrinking or steady count, not zero (zero can also mean recalculation hasn't run recently).",
    howToImprove: [
      "Work critical-severity items first — they represent the highest-confidence, highest-impact triggers.",
      "Snooze items that are already being handled elsewhere so the active count reflects only what's truly outstanding.",
      "Run Recalculate All after any bulk data change so the list reflects current reality.",
    ],
  },
  forecastAccuracy: {
    definition:
      "How closely recent demand forecasts have matched actual sales, expressed as 100 minus the average forecast error (MAPE).",
    whyItMatters:
      "Low accuracy means downstream numbers that depend on forecasts — safety stock, reorder points, demand-increase recommendations — deserve more skepticism.",
    howCalculated:
      "Per period: |actual − forecast| ÷ actual × 100 = error. Averaged across all recent forecast periods (periods with zero actual sales are excluded, never treated as 0% error), then subtracted from 100.",
    idealRange: "Above 80% is trustworthy. Below 70% (MAPE above 30%) is the threshold below which demand-trend recommendations are deliberately suppressed.",
    howToImprove: [
      "Check for products with unusually volatile or sparse sales history — MAPE is naturally noisier for low-volume SKUs.",
      "Keep demand history current with regular imports so forecasts are trained on recent patterns.",
      "Compare the two forecasting methods per product on the Demand Forecasting page — one may consistently outperform the other for a given SKU.",
    ],
  },
  overduePurchaseOrders: {
    definition:
      "Purchase orders still marked in-transit whose expected delivery date has already passed.",
    whyItMatters:
      "Each one is a delivery promise already broken — a direct, immediate procurement risk, not a forecast or a trend.",
    howCalculated:
      "A live count of PurchaseOrder rows with status IN_TRANSIT and an expectedDeliveryDate earlier than right now.",
    idealRange: "Zero is the target — any count above zero is a live delivery risk worth following up today.",
    howToImprove: [
      "Contact the supplier on each overdue order for a revised delivery date.",
      "Check whether the affected SKUs also have a critical stock position — that combination is the highest-urgency case.",
      "Mark orders RECEIVED promptly once delivered, so this count doesn't overstate current risk.",
    ],
  },
} satisfies Record<string, KpiInfoContent>;

export type KpiDefinitionKey = keyof typeof KPI_DEFINITIONS;

/**
 * The one genuinely data-dependent sentence in a KPI info panel — computed
 * from the live value, not stored as static copy. Still fully
 * deterministic (a template filled with a real number), never AI-generated.
 */
export function kpiCurrentInterpretation(key: KpiDefinitionKey, value: number | null): string {
  if (value === null) return "Not enough data yet to compute this metric.";

  switch (key) {
    case "operationsHealthScore":
      return value >= 80
        ? `Currently ${Math.round(value)}/100 — operations are in good shape.`
        : value >= 60
          ? `Currently ${Math.round(value)}/100 — needs attention in at least one area.`
          : `Currently ${Math.round(value)}/100 — requires immediate attention.`;
    case "inventoryTurnover":
      return value >= 8
        ? `Currently ${value.toFixed(1)}x/year — at or above the 8x target.`
        : `Currently ${value.toFixed(1)}x/year — below the 8x target, worth reviewing alongside stockout risk.`;
    case "supplierReliability":
      return value >= 70
        ? `Currently averaging ${Math.round(value)}/100 — above the reliability threshold.`
        : `Currently averaging ${Math.round(value)}/100 — below the 70-point reliability threshold.`;
    case "activeRecommendations":
      return `${Math.round(value)} recommendation${value === 1 ? "" : "s"} currently open.`;
    case "forecastAccuracy":
      return value >= 80
        ? `Currently ${value.toFixed(1)}% — forecasts are trustworthy.`
        : `Currently ${value.toFixed(1)}% — below the 80% trust threshold.`;
    case "overduePurchaseOrders":
      return value === 0
        ? "No purchase orders are currently overdue."
        : `${Math.round(value)} purchase order${value === 1 ? " is" : "s are"} currently overdue.`;
    default:
      return "";
  }
}
